#!/usr/bin/env python2
# -*- coding: utf-8 -*-

# This file is part of the Archivematica development tools.
#
# Copyright 2010-2016 Artefactual Systems Inc. <http://artefactual.com>
#
# Archivematica is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Archivematica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Archivematica.  If not, see <http://www.gnu.org/licenses/>.

import os, sys, subprocess, tempfile, shutil, ConfigParser
sys.path.append("/usr/lib/archivematica/archivematicaCommon")

# Determine root of shared directories
clientConfigFilePath = '/etc/archivematica/MCPClient/clientConfig.conf'
config = ConfigParser.SafeConfigParser()
config.read(clientConfigFilePath)

try:
    sharedDirectory = config.get('MCPClient', "sharedDirectoryMounted")
except:
    print "Configuration item 'sharedDirectoryMounted' not available at /etc/archivematica/MCPClient/clientConfig.conf."
    os._exit(1)

# Set root directory
try:
    rootdir = sys.argv[1]
    if not os.path.exists(rootdir):
        print "AIP store location doesn't exist."
        os._exit(1)
except:
    print 'usage: ' + sys.argv[0] + ' <path to AIP store>'
    rootdir = os.path.join(sharedDirectory, 'www/AIPsStore')
    print 'Default path is: ' + rootdir
    os._exit(1)

print "Extracting METS files from AIPS in " + rootdir + "..."

def processAIP(path, temp_dir):
    archive_file = os.path.basename(path)
    subdir = archive_file[:-3]
    aip_name = subdir[:-37]
    uuid =  archive_file[-39:-3]
    mets_file = "METS." + uuid + ".xml"
    mets_file_relative_path = subdir + "/data/" + mets_file

    print 'Processing AIP ' + uuid + '...'

    command_data = [
        '7za',
        'e',
        '-o' + temp_dir,
        path,
        mets_file_relative_path
    ]

    subprocess.call(command_data)

    pathToMETS = os.path.join(temp_dir, mets_file)

temp_dir = tempfile.mkdtemp()

for root, subFolders, files in os.walk(rootdir):
    for file in files:
        try:
            file.index('.7z')
            processAIP(os.path.join(root, file), temp_dir)
        except:
            pass

print "Cleaning up..."

#shutil.rmtree(temp_dir)

print "Files extracted to " + temp_dir + "."
