#!/usr/bin/env bash

# This file is part of the Archivematica development tools.
#
# Copyright 2010-2017 Artefactual Systems Inc. <http://artefactual.com>
#
# Archivematica is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Archivematica is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Archivematica.  If not, see <http://www.gnu.org/licenses/>.


function restart_services() {
    sudo service gearman-job-server stop
    sudo stop archivematica-mcp-server
    sudo stop archivematica-mcp-client
    sudo stop fits
    sudo service elasticsearch stop
    sudo service apache2 stop
    sudo service nginx stop
    sudo service uwsgi stop
    sleep 1

    if [ -e "/tmp/archivematicaMCPServerPID" ]
    then
    sudo kill -9 $(cat /tmp/archivematicaMCPServerPID)
    fi

    sleep 3
    sudo service elasticsearch start
    sudo service gearman-job-server start
    sudo start fits
    sudo service nginx start
    sudo service uwsgi start
    sudo start archivematica-mcp-server
    sudo start archivematica-mcp-client
    sudo service apache2 start
}

{
    [ -z "$1" ] && VERSION="1.5"
} || {
    VERSION="$1"
}

echo "version is $VERSION"
if [ $VERSION == "1.5" ]; then
    echo "If you are trying to use this command with Archivematica 1.6.0 or later,"
    echo "there is a new command 'am services', try 'am services help' for more info."
    echo " "
    restart_services
else
    {
        echo "try using the newer 'am services' command, see 'am services help' for more info."
        am services
    }
fi
