#!/bin/bash

sudo stop archivematica-mcp-server
sudo stop archivematica-mcp-client
sudo stop fits
sudo stop gearman-job-server
sudo /etc/init.d/elasticsearch stop
sleep 1

if [ -e "/tmp/archivematicaMCPServerPID" ]
then
  sudo kill -9 $(cat /tmp/archivematicaMCPServerPID)
fi

sleep 3
sudo /etc/init.d/elasticsearch start
sudo start gearman-job-server
sudo rm /tmp/archivematicaMCP*
sudo start fits
sudo start archivematica-mcp-server
sudo start archivematica-mcp-client
sudo apache2ctl restart
